Repository wecode-bootcamp-korea/43-1st-4iz-backend, pull requests merged in 2023-03, with the labels that each got.

#2 [43기 이창섭] ADD: DB 데이터 모델링
  db/migrations/20230307145232_create_users_table.sql
  db/migrations/20230307145238_create_products_table.sql
  db/migrations/20230307145245_create_subcategories_table.sql
  db/migrations/20230307145253_create_product_subcategories_table.sql
  db/migrations/20230307145259_create_product_options_table.sql
  db/migrations/20230307145312_create_carts_table.sql
  db/migrations/20230307145319_create_product_carts_table.sql
  db/migrations/20230307150345_create_order_status_table.sql
  db/migrations/20230307150352_create_orders_table.sql
  db/migrations/20230307150429_create_product_orders_table.sql
  db/migrations/20230307150433_create_shipment_table.sql
  db/migrations/20230307150438_create_payment_table.sql
Labels: 멘토 리뷰 요청

#3 [43기 류승준] ADD : 회원가입 기능
  api/controllers/index.js
  api/controllers/userController.js
  api/models/dataSource.js
  api/models/index.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/userRouter.js
  api/services/index.js
  api/services/userService.js
  api/utils/error.js
  api/utils/validation-check.js
  app.js
Labels: 멘토 리뷰 요청

#4 [43기 이창섭] ADD: 로그인 기능
  api/controllers/index.js
  api/controllers/userController.js
  api/models/dataSource.js
  api/models/index.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/userRouter.js
  api/services/index.js
  api/services/userService.js
  api/utils/error.js
  api/utils/validation-check.js
  api/utils/validation.js
  app.js
Labels: Conflict 해결 요청

#8 [43기 이창섭] ADD: 회원중복 체크 기능
  api/controllers/userController.js
  api/models/userDao.js
  api/routes/userRouter.js
  api/services/userService.js
Labels: 멘토 리뷰 요청

#10 [43기 이창섭] MODIFY: options 테이블 수정
  db/migrations/20230307145259_create_options_table.sql
Labels: 멘토 리뷰 요청

#12 [43기 이창섭] MODIFY: carts 테이블 수정
  db/migrations/20230312123700_update_carts_table.sql
Labels: 멘토 리뷰 요청

#11 [43기 이창섭] ADD: 장바구니 추가 기능
  api/controllers/cartController.js
  api/controllers/index.js
  api/controllers/userController.js
  api/models/cartDao.js
  api/models/index.js
  api/models/userDao.js
  api/routes/cartRouter.js
  api/routes/index.js
  api/services/cartService.js
  api/services/index.js
  api/services/userService.js
  api/utils/auth.js
Labels: 멘토 리뷰 요청

#14 [43기 이창섭] ADD: 장바구니 수정 기능
  api/controllers/cartController.js
  api/models/cartDao.js
  api/models/productDao.js
  api/models/userDao.js
  api/routes/cartRouter.js
  api/services/cartService.js
Labels: 멘토 리뷰 요청

#20 [43기 이창섭] MODIFY: 회원중복 기능 수정
  api/controllers/userController.js
  api/services/userService.js
  api/utils/validation.js
Labels: 멘토 리뷰 요청

#16 [43기 이창섭] ADD: 제품 목록 기능
  api/controllers/productController.js
  api/models/cartDao.js
  api/models/productDao.js
  api/models/productQueryBuilder.js
  api/routes/productRouter.js
  api/services/productService.js
Labels: 완료

#21 [43기 이창섭] ADD: 제품 상세 기능
  api/controllers/productController.js
  api/models/productDao.js
  api/routes/productRouter.js
  api/services/productService.js
Labels: 멘토 리뷰 요청

#15 [43기 이창섭] ADD: 장바구니 삭제 기능
  api/controllers/cartController.js
  api/models/cartDao.js
  api/routes/cartRouter.js
  api/services/cartService.js
Labels: 멘토 리뷰 요청

#22 [43기 이창섭] ADD: 제품 상세 테이블 생성
  db/migrations/20230307145312_create_carts_table.sql
  db/migrations/20230307150352_create_orders_table.sql
  db/migrations/20230307150429_create_product_orders_table.sql
  db/migrations/20230312123700_update_carts_table.sql
  db/migrations/20230312125437_update_orders_table.sql
  db/migrations/20230314071338_create_order_details_table.sql
Labels: 멘토 리뷰 요청

#17 [43기 이창섭] ADD: 장바구니 목록 기능
  api/controllers/cartController.js
  api/controllers/productController.js
  api/models/cartDao.js
  api/routes/cartRouter.js
  api/services/cartService.js
Labels: 멘토 리뷰 요청

#19 [43기 이창섭] ADD: 주문 추가 기능
  api/controllers/index.js
  api/controllers/orderController.js
  api/models/index.js
  api/models/orderDao.js
  api/routes/index.js
  api/routes/orderRouter.js
  api/routes/productRouter.js
  api/services/index.js
  api/services/orderService.js
  api/utils/enum.js
  api/utils/validation.js
  package-lock.json
  package.json
Labels: 멘토 리뷰 요청

#24 [43기 이창섭] MODIFY: order_details 테이블 수정 (UNIQUE 제약 조건 삭제)
  db/migrations/20230314071338_create_order_details_table.sql
Labels: 멘토 리뷰 요청

#25 [43기 이창섭] MODIFY: carts 테이블 수정 (UNIQUE 제약 조건 추가)
  db/migrations/20230307145312_create_carts_table.sql
Labels: 멘토 리뷰 요청

#26 [43기 이창섭] ADD: 제품 존재 여부 판별 기능
  api/controllers/productController.js
  api/models/productDao.js
  api/services/productService.js
Labels: Conflict 해결 요청, 완료

#29 [43기 이창섭] ADD: 제품 추천 기능 (filter.ocolor -> filter.color)
  api/models/productDao.js
Labels: 멘토 리뷰 요청

#6 [43기 류승준] ADD: 제품 상세정보
  api/controllers/productController.js
  api/routes/productRouter.js
  api/services/productService.js
Labels: 멘토 리뷰 요청

#28 [43기 이창섭] ADD: 장바구니 생성 기능 수정
  api/controllers/cartController.js
  api/models/cartDao.js
  api/services/cartService.js
Labels: 완료

#30 [43기 이창섭] ADD: 아이디가 숫자인지 판별하는 기능
  api/services/cartService.js
  api/services/orderService.js
  api/services/productService.js
  api/utils/validation.js
Labels: 완료

#31 [43기 이창섭] ADD: 장바구니 중복 확인 기능
  api/controllers/cartController.js
  api/models/cartDao.js
  api/routes/cartRouter.js
  api/services/cartService.js
  api/services/productService.js
Labels: Conflict 해결 요청
